[package]
name = "mjl"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
lazy_static = "1.5.0"
regex = "1.12.3"
mjd-workspace-hack = { version = "0.1", path = "../mjd-workspace-hack" }
